---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: drone_idf_env:0.2
    commands:
    - export IDF_TOOLS_EXPORT_CMD=/esp-idf/export.sh
    - export IDF_TOOLS_INSTALL_CMD=/esp-idf/install.sh
    - idf_exports=$(/esp-idf/tools/idf_tools.py export) || return 1
    - eval $idf_exports
    - git submodule update --init --recursive
    - idf.py build

  - name: deploy
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: deploy_host
      username:
        from_secret: ssh_username
      password:
        from_secret: ssh_password
      port: 22
      target: /var/www/ota
      source: build/t_wristband.bin

when:
  event:
    - push
    - tag


